// packages/oh-popup-react/src/components/popup/portal.tsx
import { FC, ReactNode, useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'

export interface PortalProps {
  children: ReactNode
  node?: HTMLElement
}

export const Portal: FC<PortalProps> = ({ node, children }: PortalProps) => {
  const defaultNodeRef = useRef<HTMLElement>()

  useEffect(
    () => () => {
      if (defaultNodeRef.current) {
        document.body.removeChild(defaultNodeRef.current)
      }
    },
    []
  )

  if (!node && !defaultNodeRef.current) {
    const defaultNode = (defaultNodeRef.current = document.createElement('div'))
    defaultNode.className = 'oh-popup__portal'
    document.body.appendChild(defaultNode)
  }

  return createPortal(children, (node || defaultNodeRef.current)!)
}

// packages/oh-popup-vue/src/components/popup/portal.tsx
import { defineComponent, onUnmounted, ref, Teleport } from 'vue'

export interface PortalProps {
  node?: HTMLElement
}

export const Portal = defineComponent({
  props: {
    node: {
      type: Object as () => HTMLElement | undefined,
      required: false,
    },
  },
  setup(props, { slots }) {
    const defaultNodeRef = ref<HTMLElement>()

    onUnmounted(() => {
      if (defaultNodeRef.value) {
        document.body.removeChild(defaultNodeRef.value)
      }
    })

    if (!props.node && !defaultNodeRef.value) {
      const defaultNode = (defaultNodeRef.value = document.createElement('div'))
      defaultNode.className = 'oh-popup__portal'
      document.body.appendChild(defaultNode)
    }

    return () => (
      <Teleport to={props.node || defaultNodeRef.value!}>
        {slots.default?.()}
      </Teleport>
    )
  },
})
