// packages/oh-popup-react-native/src/components/ManagerProvider.tsx
import { Popup, PopupManager } from 'oh-popup'
import { FC, useEffect, useState } from 'react'
import { ManagerContext } from '../context'
import { useUpdate } from '../hooks/useUpdate'
import { PopupProvider } from './PopupProvider'

export interface PopupProviderProps {
  manager: PopupManager
}

export const ManagerProvider: FC<PopupProviderProps> = ({ manager }) => {
  const [popups, setPopups] = useState<Popup[]>([])
  const update = useUpdate()

  useEffect(() => {
    const listener = (_popups: Popup[]) => {
      setPopups(_popups)
      update()
    }
    manager.on('change', listener as any)
    return () => manager.off('change', listener as any)
  }, [])

  return (
    <ManagerContext.Provider value={manager}>
      {popups.map((popup) => (
        <PopupProvider key={popup.key} popup={popup} />
      ))}
    </ManagerContext.Provider>
  )
}

// packages/oh-popup-vue/src/components/ManagerProvider.tsx
import { Popup, PopupManager } from 'oh-popup'
import { defineComponent, onBeforeMount, onUnmounted, provide, ref } from 'vue'
import { ManagerContext } from '../context'
import { PopupProvider } from './PopupProvider'

export interface ManagerProviderProps {
  manager: PopupManager
}

export const ManagerProvider = defineComponent({
  name: 'ManagerProvider',
  props: {
    manager: {
      type: Object as () => PopupManager,
      required: true,
    },
  },
  setup(props) {
    const popups = ref<Popup[]>([])

    onBeforeMount(() => {
      const listener = (_popups: Popup[]) => {
        popups.value = _popups
      }
      props.manager.on('change', listener)
      onUnmounted(() => props.manager.off('change', listener))
    })

    provide(ManagerContext, props.manager)

    return () => (
      <>
        {popups.value.map((popup) => (
          <PopupProvider key={popup.key} popup={popup as any} />
        ))}
      </>
    )
  },
})
